import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class DialogMenu {
    private JPanel dialogPanel;
    private JTextField questionTextField;
    private JTextField correctAnswerTextField;
    private JTextField secondAnswerTextField;
    private JTextField thirdAnswerTextField;
    private JTextField fourthAnswerTextField;
    private JLabel questionLabel;
    private JLabel correctAnswerLabel;
    private JLabel wrongAnswersLabel;

    /**
     * Constructor
     */
    public DialogMenu(Question questionObj) {
        setTextFields(questionObj);
    }

    /**
     * Fill out text fields by the given (Question) type object
     */
    private void setTextFields(Question questionObj) {
        questionTextField.setText(questionObj.getQuestion());
        correctAnswerTextField.setText(questionObj.getCorrectAnswer());
        secondAnswerTextField.setText(questionObj.getAnswers()[0]);
        thirdAnswerTextField.setText(questionObj.getAnswers()[1]);
        fourthAnswerTextField.setText(questionObj.getAnswers()[2]);
    }

    /**
     * Convert text fields to Question
     * Return (Question) type object
     */
    public Question getFieldsAsQuestion() {
        return new Question(
                questionTextField.getText(), correctAnswerTextField.getText(),
                new String[]{
                        secondAnswerTextField.getText(),
                        thirdAnswerTextField.getText(),
                        fourthAnswerTextField.getText()
                }
        );
    }

    /**
     * Pop up the DialogMenu with Cancel/OK buttons
     * Returns 0 if everything goes well, otherwise it returns -2
     */
    public int displayDialogMenu(Component parent) {
        return JOptionPane.showConfirmDialog(parent, dialogPanel, "Edit question",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dialogPanel = new JPanel();
        dialogPanel.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        questionTextField = new JTextField();
        questionTextField.setText("Type your question here");
        dialogPanel.add(questionTextField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        correctAnswerLabel = new JLabel();
        correctAnswerLabel.setText("Correct answer");
        dialogPanel.add(correctAnswerLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        wrongAnswersLabel = new JLabel();
        wrongAnswersLabel.setText("Wrong answers");
        dialogPanel.add(wrongAnswersLabel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        correctAnswerTextField = new JTextField();
        correctAnswerTextField.setText("Type here the correct answer for your question");
        dialogPanel.add(correctAnswerTextField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        secondAnswerTextField = new JTextField();
        secondAnswerTextField.setText("Type the wrong variation of answer");
        dialogPanel.add(secondAnswerTextField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        thirdAnswerTextField = new JTextField();
        thirdAnswerTextField.setText("Another wrong answer");
        dialogPanel.add(thirdAnswerTextField, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fourthAnswerTextField = new JTextField();
        fourthAnswerTextField.setText("Answer variant #4");
        dialogPanel.add(fourthAnswerTextField, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        questionLabel = new JLabel();
        questionLabel.setText("Question");
        dialogPanel.add(questionLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dialogPanel;
    }

    /**
     * Getter for Question field
     */
    public JTextField getQuestionTextField() {
        return questionTextField;
    }

}
