import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Random;

public class MainForm {
    protected static Question updatedQuestionObj, selectedQuestionObj;
    private JPanel mainPanel = new JPanel();
    private JList<Question> questionList = new JList<>();
    private JScrollPane listScroller = new JScrollPane(questionList);
    private JButton followButton;
    private JButton exitButton;
    private JLabel answerLabel;
    private DialogMenu dialog;
    private DefaultListModel<Question> model = new DefaultListModel<>();

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * __init__(self) constructor
     */
    public MainForm() {
        JFrame frame = new DrawFrame("List of questions", mainPanel);
        questionList.setModel(model);
        addDefaultElements();
        questionList.getSelectionModel().addListSelectionListener(new ListSelectionHandler());
        followButton.addActionListener(new ButtonHandler());
        exitButton.addActionListener(e -> System.exit(0));
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(MainForm::new);
    }

    /**
     * Temporary method for randomize
     */
    private static Question getRandomQuestion() {
        Random randomizer = new Random();
        int rand = randomizer.nextInt(5000);
        return new Question(
                "Q" + rand,
                "CA" + rand,
                new String[]{
                        "1A" + rand,
                        "2A" + rand,
                        "3A" + rand
                }
        );
    }

    /**
     * Reusable method for setter of the answerLabel
     */
    public void setAnswerLabelText(String answerLabel) {
        this.answerLabel.setText("Correct answer: " + answerLabel);
    }

    /**
     * Temporary method to fill out the question properties
     */
    private void addDefaultElements() {
        for (int i = 0; i < 5; i++) {
            model.addElement(getRandomQuestion());
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        listScroller = new JScrollPane();
        mainPanel.add(listScroller, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        questionList = new JList();
        questionList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        questionList.setModel(defaultListModel1);
        questionList.setSelectionMode(0);
        listScroller.setViewportView(questionList);
        answerLabel = new JLabel();
        answerLabel.setText("Answer");
        mainPanel.add(answerLabel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        followButton = new JButton();
        followButton.setText("Follow");
        mainPanel.add(followButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exitButton = new JButton();
        exitButton.setText("Exit");
        mainPanel.add(exitButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    /**
     * Handle select-event of JList and find out the selected item
     * Assign a static var to use it for dialogMenu later on
     * Update the answerLabel with the correct answer
     */
    class ListSelectionHandler implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent event) {
            selectedQuestionObj = questionList.getSelectedValue();
            setAnswerLabelText(selectedQuestionObj.getCorrectAnswer());
        }
    }

    /**
     * Handle click-event of the button Follow
     * Open a new dialog menu to edit the selected question
     */
    class ButtonHandler extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent event) {
            int selectedQuestionIndex = model.indexOf(selectedQuestionObj);
            dialog = new DialogMenu(selectedQuestionObj);
            int result = dialog.displayDialogMenu(mainPanel);
            if (result == JOptionPane.OK_OPTION) {
                updatedQuestionObj = dialog.getFieldsAsQuestion();
                model.setElementAt(updatedQuestionObj, selectedQuestionIndex);
                // Update answerLabel immediately
                setAnswerLabelText(updatedQuestionObj.getCorrectAnswer());
                // Test output
                System.out.println("Updated to " + updatedQuestionObj.toString());
            } else {
                System.out.println("Cancelled!");
            }
        }
    }
}
